### ISSUE TITLE
Regenerate your token

### ISSUE THREAD

**Issue by TildeBeta** [Suboptimal-Guild/Discord-Bots#5]
Your bot's token is in the harambot.py file which allows anyone to log in and do whatever they want with your bot.

Go to https://discordapp.com/developers/applications/me and regenerate your bot's token from there.
Do not put the new token in the repository.

In the future use config files and .gitignore said files.

**Comment by ihanken** [comment]
Just put the files into a tokens file and our local machines and put it in a .gitignore. We were being lazy, but it should have been done a lot sooner.
